### ISSUE TITLE
Hi! 

### ISSUE THREAD

**Issue by mrszalkai** [Katrixerse/Justin#2]
### Hi Syntheti! My question is, in what file can I write the default prefix? ###

**Comment by pika32223** [comment]
should be in start.js

**Comment by Syntheti** [comment]
The prefix is written to an sqlite db which can be modified with sqlite browser if you need to change it.

**Comment by pika32223** [comment]
Great Job! suggestion. can you make a Discord Moderation bot in js? with a config command to change the prefix, logs, welcome, etc... alot of people would love that.
Thanks!
